apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: scanbypass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: ghcr.io/internshippoc/my-couchdb:latest
        ports:
        - containerPort: 5984
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: COUCHDB_USER
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: COUCHDB_PASSWORD
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
      volumes:
      - name: couchdb-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: scanbypass
spec:
  ports:
  - port: 5984
    targetPort: 5984
  selector:
    app: couchdb
