apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: ghcr.io/internshippoc/my-couchdb:3
        ports:
        - containerPort: 5984
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: COUCHDB_USER
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: COUCHDB_PASSWORD
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
      volumes:
      - name: couchdb-data
        emptyDir: {}
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
spec:
  ports:
  - port: 5984
    targetPort: 5984
  selector:
    app: couchdb
---
apiVersion: batch/v1
kind: Job
metadata:
  name: couchdb-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-couchdb
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          until curl -s http://adm:pass@127.0.0.1:5984/_up; do
            echo "Waiting for CouchDB..."
            sleep 2
          done

          curl -X PUT http://adm:pass@127.0.0.1:5984/_users
          curl -X PUT http://adm:pass@127.0.0.1:5984/_replicator
          curl -X PUT http://adm:pass@127.0.0.1:5984/_global_changes
