---
apiVersion: v1
kind: Namespace
metadata:
  name: scanbypass

---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: scanbypass
type: Opaque
stringData:
  COUCHDB_USER: admin
  COUCHDB_PASSWORD: admin

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pvc
  namespace: scanbypass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: scanbypass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3
        ports:
          - containerPort: 5984
        env:
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: couchdb-secret
                key: COUCHDB_USER
          - name: COUCHDB_PASS
            valueFrom:
              secretKeyRef:
                name: couchdb-secret
                key: COUCHDB_PASSWORD
        volumeMounts:
          - mountPath: /opt/couchdb/data
            name: couchdb-data
      volumes:
        - name: couchdb-data
          persistentVolumeClaim:
            claimName: couchdb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: scanbypass
spec:
  selector:
    app: couchdb
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: scanbypass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ghcr.io/internshippoc/scanbypasspoc/front:latest
        ports:
          - containerPort: 5000
        env:
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: couchdb-secret
                key: COUCHDB_USER
          - name: COUCHDB_PASS
            valueFrom:
              secretKeyRef:
                name: couchdb-secret
                key: COUCHDB_PASSWORD
          - name: COUCHDB_HOST
            value: couchdb
          - name: COUCHDB_PORT
            value: "5984"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: scanbypass
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  
