name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: flask-couchdb-app
  REGISTRY: ghcr.io/internshippoc/scanbypasspoc

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: InternshipPOC
        password: ${{ secrets.GITNOTHUB_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Front-end
        file: ./Front-end/Dockerfile
        push: true
        tags: ghcr.io/internshippoc/scanbypasspoc/front:latest

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/internshippoc/scanbypasspoc/front:latest
